all: check_ordering buddy_bitmap draw_circle edit_distance floating_point \
	 longest_abs_filepath longest_pallindrome_subsequence max_subsequence non_adjecent_max_sum \
	 normalize_path pallindromes_in_string quick_sort spiral_matrix \
	 4sum 2sum stack is_number running_maximum heap roman_decimal \
	 doubly_ll isomorphic replace_string permute select range matrix_path \
	 longest_pallindrome_substring moving_points

moving_points : moving_points.cpp
	g++ --std=c++11 moving_points.cpp -o /tmp/practice/moving_points -g

longest_pallindrome_substring: longest_pallindrome.cpp
	g++ --std=c++11 longest_pallindrome.cpp -o /tmp/practice/longest_pallindrome_substring -g

matrix_path: matrix_path.cpp
	g++ --std=c++11 matrix_path.cpp -o /tmp/practice/matrix_path -g

range: range.cpp
	g++ --std=c++11 range.cpp -o /tmp/practice/range -g

select: string_combinations.cpp
	g++ --std=c++11 string_combinations.cpp -o /tmp/practice/select -g

permute: string_permutation.cpp
	g++ --std=c++11 string_permutation.cpp -o /tmp/practice/permute -g

replace_string: replace_string.cpp
	g++ --std=c++11 replace_string.cpp -o /tmp/practice/replace_string -g

merge_ll: merge_sorted_ll.cpp
	g++ --std=c++11 merge_sorted_ll.cpp -o /tmp/practice/merge_ll -g

doubly_ll: doubly_ll.cpp
	g++ --std=c++11 doubly_ll.cpp -o /tmp/practice/doubly_ll -g

roman_decimal: roman_to_decimal.cpp
	g++ --std=c++11 roman_to_decimal.cpp -o /tmp/practice/roman_decimal -g

encoding: check_encoding.cpp
	g++ --std=c++11 check_encoding.cpp -o /tmp/practice/encoding -g

heap: test_heap.cpp
	g++ --std=c++11 test_heap.cpp -o /tmp/practice/heap -g

running_maximum: running_maximum.cpp
	g++ --std=c++11 running_maximum.cpp -o /tmp/practice/running_maximum -g

is_number: string_is_number.cpp
	g++ --std=c++11 string_is_number.cpp -o /tmp/practice/is_number -g

2sum: two_sum.cpp
	g++ --std=c++11 two_sum.cpp -o /tmp/practice/2sum -g

4sum: 4sum.cpp
	g++ --std=c++11 4sum.cpp -o /tmp/practice/4sum -g

isomorphic: isomorphic.cpp
	g++ --std=c++11 isomorphic.cpp -o /tmp/practice/isomorphic -g

combinations: combinations.cpp
	g++ --std=c++11 combinations.cpp -o /tmp/practice/combinations -g

check_ordering: check_ordering.cpp
	g++ --std=c++11 check_ordering.cpp -o /tmp/practice/check_ordering -g

buddy_bitmap: buddy_bitmap.cpp
	g++ --std=c++11 -o /tmp/practice/buddy_bitmap -g buddy_bitmap.cpp

check_bst: check_bst.cpp
	g++ --std=c++11 -o /tmp/practice/check_bst -g check_bst.cpp

draw_circle: draw_circle.cpp
	g++ --std=c++11 -o /tmp/practice/draw_circle -g draw_circle.cpp

edit_distance: edit_distance.cpp
	g++ --std=c++11 -o /tmp/practice/edit_distance -g edit_distance.cpp

floating_point: floating_point.cpp
	g++ --std=c++11 -o /tmp/practice/floating_point -g floating_point.cpp

happy_number: happy_number.cpp
	g++ --std=c++11 -o /tmp/practice/happy_number -g happy_number.cpp

longest_abs_filepath: longest_abs_filepath.cpp
	g++ --std=c++11 -o /tmp/practice/longest_abs_filepath -g longest_abs_filepath.cpp

longest_pallindrome_subsequence: longest_pallindrome_subsequence.cpp
	g++ --std=c++11 -o /tmp/practice/longest_pallindrome_subsequence -g longest_pallindrome_subsequence.cpp

max_subsequence: max_subsequence.cpp
	g++ --std=c++11 -o /tmp/practice/max_subsequence -g max_subsequence.cpp

non_adjecent_max_sum: non_adjecent_max_sum.cpp
	g++ --std=c++11 -o /tmp/practice/non_adjecent_max_sum -g non_adjecent_max_sum.cpp

normalize_path: normalize_path.cpp
	g++ --std=c++11 -o /tmp/practice/normalize_path -g normalize_path.cpp

pallindromes_in_string: pallindromes_in_string.cpp
	g++ --std=c++11 -o /tmp/practice/pallindromes_in_string -g pallindromes_in_string.cpp

quick_sort: quick_sort.cpp
	g++ --std=c++11 -o /tmp/practice/quick_sort -g quick_sort.cpp

random_linkedlist_copy: random_linkedlist_copy.cpp
	g++ --std=c++11 -o /tmp/practice/random_linkedlist_copy -g random_linkedlist_copy.cpp

remove_linked_list: remove_linked_list.cpp
	g++ --std=c++11 -o /tmp/practice/remove_linked_list -g remove_linked_list.cpp

reverse_linked_list: reverse_linked_list.cpp
	g++ --std=c++11 -o /tmp/practice/reverse_linked_list -g reverse_linked_list.cpp

run_length_encoding: run_length_encoding.cpp
	g++ --std=c++11 -o /tmp/practice/run_length_encoding -g run_length_encoding.cpp

scratch: scratch.cpp
	g++ --std=c++11 -o /tmp/practice/scratch -g scratch.cpp

serialize_tree_to_list: serialize_tree_to_list.cpp
	g++ --std=c++11 -o /tmp/practice/serialize_tree_to_list -g serialize_tree_to_list.cpp

spiral_matrix: spiral_matrix.cpp
	g++ --std=c++11 -o /tmp/practice/spiral_matrix -g spiral_matrix.cpp

stack: stack.cpp
	g++ --std=c++11 -o /tmp/practice/stack -g stack.cpp

clean:
	rm -rf /tmp/practice/
