all: check_ordering buddy_bitmap draw_circle edit_distance floating_point \
	 longest_abs_filepath longest_pallindrome_subsequence max_subsequence non_adjecent_max_sum \
	 normalize_path pallindromes_in_string quick_sort spiral_matrix stack

4sum: 4sum.cpp
	g++ --std=c++11 4sum.cpp -o /tmp/practice/4sum -g

combinations: combinations.cpp
	g++ --std=c++11 combinations.cpp -o /tmp/practice/combinations -g

check_ordering: check_ordering.cpp
	g++ --std=c++11 check_ordering.cpp -o /tmp/practice/check_ordering -g

buddy_bitmap: buddy_bitmap.cpp
	g++ --std=c++11 -o /tmp/practice/buddy_bitmap -g buddy_bitmap.cpp

check_bst: check_bst.cpp
	g++ --std=c++11 -o /tmp/practice/check_bst -g check_bst.cpp

draw_circle: draw_circle.cpp
	g++ --std=c++11 -o /tmp/practice/draw_circle -g draw_circle.cpp

edit_distance: edit_distance.cpp
	g++ --std=c++11 -o /tmp/practice/edit_distance -g edit_distance.cpp

floating_point: floating_point.cpp
	g++ --std=c++11 -o /tmp/practice/floating_point -g floating_point.cpp

happy_number: happy_number.cpp
	g++ --std=c++11 -o /tmp/practice/happy_number -g happy_number.cpp

longest_abs_filepath: longest_abs_filepath.cpp
	g++ --std=c++11 -o /tmp/practice/longest_abs_filepath -g longest_abs_filepath.cpp

longest_pallindrome_subsequence: longest_pallindrome_subsequence.cpp
	g++ --std=c++11 -o /tmp/practice/longest_pallindrome_subsequence -g longest_pallindrome_subsequence.cpp

max_subsequence: max_subsequence.cpp
	g++ --std=c++11 -o /tmp/practice/max_subsequence -g max_subsequence.cpp

non_adjecent_max_sum: non_adjecent_max_sum.cpp
	g++ --std=c++11 -o /tmp/practice/non_adjecent_max_sum -g non_adjecent_max_sum.cpp

normalize_path: normalize_path.cpp
	g++ --std=c++11 -o /tmp/practice/normalize_path -g normalize_path.cpp

pallindromes_in_string: pallindromes_in_string.cpp
	g++ --std=c++11 -o /tmp/practice/pallindromes_in_string -g pallindromes_in_string.cpp

quick_sort: quick_sort.cpp
	g++ --std=c++11 -o /tmp/practice/quick_sort -g quick_sort.cpp

random_linkedlist_copy: random_linkedlist_copy.cpp
	g++ --std=c++11 -o /tmp/practice/random_linkedlist_copy -g random_linkedlist_copy.cpp

remove_linked_list: remove_linked_list.cpp
	g++ --std=c++11 -o /tmp/practice/remove_linked_list -g remove_linked_list.cpp

reverse_linked_list: reverse_linked_list.cpp
	g++ --std=c++11 -o /tmp/practice/reverse_linked_list -g reverse_linked_list.cpp

run_length_encoding: run_length_encoding.cpp
	g++ --std=c++11 -o /tmp/practice/run_length_encoding -g run_length_encoding.cpp

scratch: scratch.cpp
	g++ --std=c++11 -o /tmp/practice/scratch -g scratch.cpp

serialize_tree_to_list: serialize_tree_to_list.cpp
	g++ --std=c++11 -o /tmp/practice/serialize_tree_to_list -g serialize_tree_to_list.cpp

spiral_matrix: spiral_matrix.cpp
	g++ --std=c++11 -o /tmp/practice/spiral_matrix -g spiral_matrix.cpp

stack: stack.cpp
	g++ --std=c++11 -o /tmp/practice/stack -g stack.cpp

clean:
	rm -rf /tmp/practice/
